### ISSUE TITLE
Build fails if TE_BASE/config.xml doesn't exist

### ISSUE THREAD

**Issue by shane-axiom** [opengeospatial/teamengine#83]
The build is currently dependent on the user's environment, because it will fail if TE_BASE/config.xml doesn't exist. The offending code is in [SetupOptions.recordingInfo](https://github.com/opengeospatial/teamengine/blob/master/teamengine-core/src/main/java/com/occamlab/te/SetupOptions.java#L99).

Probably relevant to https://github.com/opengeospatial/teamengine/issues/56.

**Comment by upendra-sachan** [comment]
Resolved this issue.

**Comment by shane-axiom** [comment]
Sorry, this commit didn't fix the error when TE_BASE exists but TE_BASE/config.xml does not.

**Comment by shane-axiom** [comment]
Pull request #85 should fix.
